// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WEB.INV.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250201063455_4")]
    partial class _4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("NTI.INV.Permisos", b =>
                {
                    b.Property<string>("IdPermisos")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TipoPermiso")
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdPermisos");

                    b.ToTable("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
