// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WEB.INV.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250201064731_7")]
    partial class _7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("NTI.INV.Categoria", b =>
                {
                    b.Property<string>("IdCategoria")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("NTI.INV.Permisos", b =>
                {
                    b.Property<string>("IdPermisos")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TipoPermiso")
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdPermisos");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("NTI.INV.Productos", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("IdCategoria")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(16,2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("NTI.INV.Usuarios", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Correo")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdPermisos")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Usuario")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Codigo");

                    b.HasIndex("IdPermisos");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("NTI.INV.Productos", b =>
                {
                    b.HasOne("NTI.INV.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("NTI.INV.Usuarios", b =>
                {
                    b.HasOne("NTI.INV.Permisos", "Permisos")
                        .WithMany()
                        .HasForeignKey("IdPermisos");

                    b.Navigation("Permisos");
                });
#pragma warning restore 612, 618
        }
    }
}
